class Constants {
  static Map<String, String> categories = {
    "business": "Business",
    "entertainment": "Entertainment",
    "general": "General",
    "health": "Health",
    "science": "Science",
    "sports": "Sports",
    "technology": "Technology"
  };

  static Map<String, String> countries = {
    "ar": "Argentina",
    "au": "Australia",
    "at": "Austria",
    "be": "Belgium",
    "br": "Brazil",
    "bg": "Bulgaria",
    "ca": "Canada",
    "cn": "China",
    "co": "Colombia",
    "cu": "Cuba",
    "cz": "Czech Republic",
    "eg": "Egypt",
    "fr": "France",
    "de": "Germany",
    "gr": "Greece",
    "hk": "Hong Kong",
    "hu": "Hungary",
    "in": "India",
    "id": "Indonesia",
    "ie": "Ireland",
    "il": "Israel",
    "it": "Italy",
    "jp": "Japan",
    "lv": "Latvia",
    "lt": "Lithuania",
    "my": "Malaysia",
    "mx": "Mexico",
    "ma": "Morocco",
    "nl": "Netherlands",
    "nz": "New Zealand",
    "ng": "Nigeria",
    "no": "Norway",
    "ph": "Philippines",
    "pl": "Poland",
    "pt": "Portugal",
    "ro": "Romania",
    "ru": "Russia",
    "sa": "Saudi Arabia",
    "rs": "Serbia",
    "sg": "Singapore",
    "sk": "Slovakia",
    "si": "Slovenia",
    "za": "South Africa",
    "kr": "South Korea",
    "se": "Sweden",
    "ch": "Switzerland",
    "tw": "Taiwan",
    "th": "Thailand",
    "tr": "Turkey",
    "ae": "UAE",
    "ua": "Ukraine",
    "gb": "United Kingdom",
    "us": "United States",
    "ve": "Venuzuela",
  };

  static Map<String, String> languages = {
    "ar": "Arabic",
    "de": "German",
    "en": "English",
    "es": "Spanish",
    "fr ": "French",
    "he ": "Hebrew",
    "it ": "Italian",
    "nl ": "Dutch",
    "no ": "Norwegian",
    "pt ": "Portuguese",
    "ru ": "Russia",
    "sv ": "Swedish",
    "ud ": "Urdu",
    "zh": "Chinese"
  };
}
